/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ICodex:directionDownRight': typeof import('~icons/codex/direction-down-right')['default']
    'ICodex:loader': typeof import('~icons/codex/loader')['default']
  }
}

// For TSX support
declare global {
  const 'ICodex:directionDownRight': typeof import('~icons/codex/direction-down-right')['default']
  const 'ICodex:loader': typeof import('~icons/codex/loader')['default']
}